from api.oms_new.oms_ import Oms


class OrderList(Oms):
    method = 'get'
    api = '/omsapi/order/info'
    data = {}

    error_resp = {
        'code': 400000,
        'message': '没有可以购买的商品'
    }

    expected_schema1 = {
    "$schema":"http://json-schema.org/draft-06/schema#",
    "title":"expected_data",
    "type":"object",
    "required":[
        "code",
        "message",
        "payload"
    ],
    "properties":{
        "code":{
            "type":"number"
        },
        "message":{
            "type":"string"
        },
        "payload":{
            "type":"object",
            "required":[
                "filterRule",
                "tableHeader",
                "rowActions",
                "tableTabs",
                "options"
            ],
            "properties":{
                "filterRule":{
                    "type":"array",
                    "items":{
                        "type":"object",
                        "properties":{
                            "title":{
                                "type":"string"
                            },
                            "field":{
                                "type":"string"
                            },
                            "type":{
                                "type":"string"
                            },
                            "value":{
                                "type":"string"
                            },
                            "props":{
                                "type":"object",
                                "required":[
                                    "placeholder",
                                    "style"
                                ],
                                "properties":{
                                    "placeholder":{
                                        "type":"string"
                                    },
                                    "style":{
                                        "type":"string"
                                    }
                                }
                            },
                            "search_type":{
                                "type":"string"
                            }
                        }
                    }
                },
                "tableHeader":{
                    "type":"array",
                    "items":{
                        "type":"object",
                        "properties":{
                            "field":{
                                "type":"string"
                            },
                            "title":{
                                "type":"string"
                            },
                            "width":{
                                "type":"number"
                            },
                            "virtual_field":{
                                "type":"boolean"
                            }
                        }
                    }
                },
                "rowActions":{
                    "type":"array",
                    "items":{
                        "type":"object",
                        "properties":{
                            "text":{
                                "type":"string"
                            },
                            "type":{
                                "type":"string"
                            },
                            "target":{
                                "type":"string"
                            },
                            "props":{
                                "type":"object",
                                "required":[
                                    "icon",
                                    "circle",
                                    "size",
                                    "type"
                                ],
                                "properties":{
                                    "icon":{
                                        "type":"string"
                                    },
                                    "circle":{
                                        "type":"boolean"
                                    },
                                    "size":{
                                        "type":"string"
                                    },
                                    "type":{
                                        "type":"string"
                                    }
                                }
                            },
                            "rules":{
                                "type":"object",
                                "required":[
                                    "form_ui"
                                ],
                                "properties":{
                                    "form_ui":{
                                        "type":"array",
                                        "items":{
                                            "type":"object",
                                            "properties":{

                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "tableTabs":{
                    "type":"array",
                    "items":{
                        "type":"object",
                        "properties":{

                        }
                    }
                },
                "options":{
                    "type":"object",
                    "required":[
                        "form_path",
                        "rowChangeApi",
                        "batchButtons",
                        "enum",
                        "createAble",
                        "exportAble",
                        "defaultList",
                        "importAble",
                        "paginationEnable",
                        "topActions",
                        "tableOptions",
                        "noticeAble"
                    ],
                    "properties":{
                        "form_path":{
                            "type":"string"
                        },
                        "rowChangeApi":{
                            "type":"string"
                        },
                        "batchButtons":{
                            "type":"array",
                            "items":{
                                "type":"object",
                                "properties":{
                                    "text":{
                                        "type":"string"
                                    },
                                    "type":{
                                        "type":"string"
                                    },
                                    "target":{
                                        "type":"string"
                                    },
                                    "props":{
                                        "type":"object",
                                        "required":[
                                            "icon",
                                            "circle",
                                            "size",
                                            "type"
                                        ],
                                        "properties":{
                                            "icon":{
                                                "type":"string"
                                            },
                                            "circle":{
                                                "type":"boolean"
                                            },
                                            "size":{
                                                "type":"string"
                                            },
                                            "type":{
                                                "type":"string"
                                            }
                                        }
                                    },
                                    "rules":{
                                        "type":"object",
                                        "required":[
                                            "form",
                                            "compute_map",
                                            "form_ui"
                                        ],
                                        "properties":{
                                            "form":{
                                                "type":"array",
                                                "items":{
                                                    "type":"object",
                                                    "properties":{
                                                        "title":{
                                                            "type":"string"
                                                        },
                                                        "field":{
                                                            "type":"string"
                                                        },
                                                        "type":{
                                                            "type":"string"
                                                        },
                                                        "value":{
                                                            "type":"string"
                                                        }
                                                    }
                                                }
                                            },
                                            "compute_map":{
                                                "type":"object",
                                                "required":[

                                                ],
                                                "properties":{

                                                }
                                            },
                                            "form_ui":{
                                                "type":"array",
                                                "items":{
                                                    "type":"object",
                                                    "properties":{

                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "enum":{
                            "type":"array",
                            "items":{
                                "type":"object",
                                "properties":{

                                }
                            }
                        },
                        "createAble":{
                            "type":"boolean"
                        },
                        "exportAble":{
                            "type":"boolean"
                        },
                        "defaultList":{
                            "type":"boolean"
                        },
                        "importAble":{
                            "type":"boolean"
                        },
                        "paginationEnable":{
                            "type":"boolean"
                        },
                        "topActions":{
                            "type":"array",
                            "items":{
                                "type":"object",
                                "properties":{

                                }
                            }
                        },
                        "tableOptions":{
                            "type":"object",
                            "required":[
                                "style",
                                "group"
                            ],
                            "properties":{
                                "style":{
                                    "type":"string"
                                },
                                "group":{
                                    "type":"array",
                                    "items":{
                                        "type":"object",
                                        "properties":{

                                        }
                                    }
                                }
                            }
                        },
                        "noticeAble":{
                            "type":"boolean"
                        }
                    }
                }
            }
        }
    }
}
