# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mengtui/core/core.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mengtui/core/core.proto',
  package='mengtui.core',
  syntax='proto3',
  serialized_options=b'Z+ptapp.cn/interface/golang/mengtui/core;core',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17mengtui/core/core.proto\x12\x0cmengtui.core\x1a google/protobuf/descriptor.proto:;\n\x14\x63ompatible_pb_prefix\x12\x1c.google.protobuf.FileOptions\x18\xe8\x07 \x01(\t:D\n\x1aservice_default_timeout_ms\x12\x1f.google.protobuf.ServiceOptions\x18\xe8\x07 \x01(\x03:B\n\x19method_default_timeout_ms\x12\x1e.google.protobuf.MethodOptions\x18\xe8\x07 \x01(\x03\x42-Z+ptapp.cn/interface/golang/mengtui/core;coreb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


COMPATIBLE_PB_PREFIX_FIELD_NUMBER = 1000
compatible_pb_prefix = _descriptor.FieldDescriptor(
  name='compatible_pb_prefix', full_name='mengtui.core.compatible_pb_prefix', index=0,
  number=1000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SERVICE_DEFAULT_TIMEOUT_MS_FIELD_NUMBER = 1000
service_default_timeout_ms = _descriptor.FieldDescriptor(
  name='service_default_timeout_ms', full_name='mengtui.core.service_default_timeout_ms', index=1,
  number=1000, type=3, cpp_type=2, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
METHOD_DEFAULT_TIMEOUT_MS_FIELD_NUMBER = 1000
method_default_timeout_ms = _descriptor.FieldDescriptor(
  name='method_default_timeout_ms', full_name='mengtui.core.method_default_timeout_ms', index=2,
  number=1000, type=3, cpp_type=2, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['compatible_pb_prefix'] = compatible_pb_prefix
DESCRIPTOR.extensions_by_name['service_default_timeout_ms'] = service_default_timeout_ms
DESCRIPTOR.extensions_by_name['method_default_timeout_ms'] = method_default_timeout_ms
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(compatible_pb_prefix)
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(service_default_timeout_ms)
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(method_default_timeout_ms)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
